name: 'Windows Service Action'

description: 'This action will start, stop or restart a Windows service on an on-prem Windows OS machine.'

inputs:
  action:
    description: 'Specify start, stop, or restart action to perform'
    default: 'start'
    required: true
  service-name:
    description: 'The name of the Windows service to perform the action on'
    required: true
  server:
    description: 'The name of the target server'
    required: true
  service-account-id:
    description: 'The service account name'
    required: true
  service-account-password:
    description: 'The service account password'
    required: true
  server-cert-path:
    description: 'Path to remote server public ssl cert'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Action
      id: action
      shell: powershell
      run: |
        $secure_password = ConvertTo-SecureString -String '${{ inputs.service-account-password }}' -AsPlainText -Force
        ${{ github.action_path }}/service_action.ps1 `
          -action '${{ inputs.action }}'.ToLower() `
          -service_name '${{ inputs.service-name }}' `
          -server '${{ inputs.server }}' `
          -user_id '${{ inputs.service-account-id }}' `
          -password $secure_password `
          -cert_path '${{ inputs.server-cert-path }}'
